- reference/gcp-redis.html.md.erb
- reference/gcp-storage.html.md.erb
- reference/index.html.md.erb
Co-authored-by: Marcela Campo <mcampo@pivotal.io>
> new services docs for gcp

- reference/gcp-spanner.html.md.erb
Co-authored-by: Marcela Campo <mcampo@pivotal.io>
Co-authored-by: Felisia Martini <fmartini@pivotal.io>
> spanner docs

- reference/gcp-stackdrivertrace.html.md.erb
> Docs for Strackdriver Trace service

- reference/gcp-dataproc.html.md.erb
- reference/gcp-mysql.html.md.erb
- reference/gcp-postgresql.html.md.erb
- reference/gcp-redis.html.md.erb
- reference/gcp-spanner.html.md.erb
- reference/gcp-stack-driver-trace.html.md.erb
- reference/gcp-storage.html.md.erb
- reference/index.html.md.erb
[#181062391](https://www.pivotaltracker.com/story/show/181062391)
> Added beta label and warning to all services

- reference/gcp-postgresql.html.md.erb
This should be merged to master and 0.2
> Add public ips and authorized CIDR parameters

- reference/gcp-postgresql.html.md.erb
Co-Authored-By: Marcela Campo <20945140+pivotal-marcela-campo@users.noreply.github.com>
> Add details for binding on postgres

- installing-with-gcp.html.md.erb
> Add more details on APIs needed in GCP

- reference/gcp-postgresql.html.md.erb
Not merged with 0.2, to be merged on the release after that.
cc: @FelisiaM
> Add TLS flag to postgres docs

- reference/gcp-postgresql.html.md.erb
This feature will be exposed in the first major release
[#181060141](https://www.pivotaltracker.com/story/show/181060141)
> docs: backup properties for PostgreSQL

- installing-with-gcp.html.md.erb
[#181848961](https://www.pivotaltracker.com/story/show/181848961)
Please merge to 0.2 branch as well
> clarify state database setup

- reference/gcp-postgresql.html.md.erb
[#181059796](https://www.pivotaltracker.com/story/show/181059796)
Co-Authored-By: Jatin Naik <451613+tinygrasshopper@users.noreply.github.com>
> Document require_ssl

- reference/gcp-postgresql.html.md.erb
Here are a number of small edits relating to docs testing that we have done. Each commit is for one issue.
> docs: updates for GA

- installing-with-gcp.html.md.erb
These notes are present in the Azure docs and make sense here too
[#181523458](https://www.pivotaltracker.com/story/show/181523458)
Also cherry-pick to 1.0 branch please
> Add references to other sections

- index.html.md.erb
- release-notes.html.md.erb
- upgrading.html.md.erb
This is for the upcoming 1.1.0 release.
> add release notes for 1.1.0

- reference/gcp-postgresql.html.md.erb
Please also cherry-pick to:
- 1.1
- 1.0
> postgresql: update note on binding user

- gcp-postgres-migration.html.md.erb
we also need this commit in 1.1 branch
> Add docs gcp service instance migration guide#182901990

- reference/gcp-mysql.html.md.erb
[#183701212](https://www.pivotaltracker.com/story/show/183701212)
> docs: [mysql] Set minimum to match multipleOf

- upgrading.html.md.erb
[#183876725](https://www.pivotaltracker.com/story/show/183876725)
None
> chore: fix HTML structure

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
[#183886021](https://www.pivotaltracker.com/story/show/183886021)
None
> MySQL: Expose MySQL version property

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
[#183885800](https://www.pivotaltracker.com/story/show/183885800)
None
> MySQL: expose deletion protection

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
> chore: improve readability

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
> chore: improve readability adding link to the docs

- release-notes.html.md.erb
[#183975670](https://www.pivotaltracker.com/story/show/183975670)
None
> MySQL: Match password policy with PostgreSQL

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
[#183876959](https://www.pivotaltracker.com/story/show/183876959)
None
> MySQL backup configuration

- reference/gcp-mysql.html.md.erb
- reference/gcp-postgresql.html.md.erb
- release-notes.html.md.erb
None
[#183876947](https://www.pivotaltracker.com/story/show/183876947)
> [#183876947] Enable public ip

- installing-with-gcp.html.md.erb
- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
[#184051243](https://www.pivotaltracker.com/story/show/184051243)
None
> GCP MySQL: remove the built-in plans

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
- upgrading.html.md.erb
[#183975388](https://www.pivotaltracker.com/story/show/183975388)
None
> GCP MySQL: remove authorized_network parameter

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
[#181059904](https://www.pivotaltracker.com/story/show/181059904)
None
> Update MySQL binding details

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184053361](https://www.pivotaltracker.com/story/show/184053361)
None
> GCP Storage: binding result using snake case format

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184053404](https://www.pivotaltracker.com/story/show/184053404)
None
> GCP Storage: remove acl plan parameter

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184044557](https://www.pivotaltracker.com/story/show/184044557)
None
> Cloud Storage: Multi-Regional class by default

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184044557](https://www.pivotaltracker.com/story/show/184044557)
None
> GCP Storage: US as a default region

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184044692](https://www.pivotaltracker.com/story/show/184044692)
None
> GCP Storage: expose dual-region configuration

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184044836](https://www.pivotaltracker.com/story/show/184044836)
None
> GCP Storage: expose versioning

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184044702](https://www.pivotaltracker.com/story/show/184044702)
None
> Storage: expose uniform_bucket_level_access

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184045199](https://www.pivotaltracker.com/story/show/184045199)
- none
> docs: [storage] public_access_prevention property

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184044836](https://www.pivotaltracker.com/story/show/184044836)
None
> Storage: versioning false by default

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184045227](https://www.pivotaltracker.com/story/show/184045227)
None
> Storage: expose encryption configuration

- release-notes.html.md.erb
[#184044692](https://www.pivotaltracker.com/story/show/184044692)
None
> Cloud Storage: add example dual-region configuration

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184044702](https://www.pivotaltracker.com/story/show/184044702)
None
> Storage: IAM set false by default

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184045227](https://www.pivotaltracker.com/story/show/184045227)
None
> chore: use the right default value to avoid misunderstandings

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184053043](https://www.pivotaltracker.com/story/show/184053043)
None
> GCP Storage: expose autoclass

- reference/gcp-storage.html.md.erb
This note is already in the release notes, and it's helpful to duplicate it here https://github.com/pivotal-cf/docs-csb-gcp/pull/57
- none
> storage: add note relating to dual region

- reference/gcp-mysql.html.md.erb
- upgrading.html.md.erb
> docs: Bump MySQL version to 8.0

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184045402](https://www.pivotaltracker.com/story/show/184045402)
None
> GCP Storage: expose retention_policy

- reference/gcp-storage.html.md.erb
[#184045402](https://www.pivotaltracker.com/story/show/184045402)
None
> Cloud Storage: improve autoclass feature documentation

- release-notes.html.md.erb
[#180913283](https://www.pivotaltracker.com/story/show/180913283)
None
> GCP MySQL: TLS alwasy enabled

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
[#184303419](https://www.pivotaltracker.com/story/show/184303419)
None
> docs: MySQL HA Configuration

- reference/gcp-mysql.html.md.erb
[#184303419](https://www.pivotaltracker.com/story/show/184303419)
None
> docs: Reword HA documentation

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184051938](https://www.pivotaltracker.com/story/show/184051938)
- none
> docs: add `predefined_acl` property

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184053558](https://www.pivotaltracker.com/story/show/184053558)
None
> Cloud Storage: Improve constraints in bucket name property

- installing-with-gcp.html.md.erb
- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184053110](https://www.pivotaltracker.com/story/show/184053110)
None
> GCP Storage: delete built-in plans

- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
[#184278537](https://www.pivotaltracker.com/story/show/184278537)
None
> docs: Describe TLS connectivity

- reference/gcp-mysql.html.md.erb
- reference/gcp-storage.html.md.erb
[#184414129](https://www.pivotaltracker.com/story/show/184414129)
- none
> fix: displayName for example services

- release-notes.html.md.erb
- upgrading.html.md.erb
[#184053110](https://www.pivotaltracker.com/story/show/184053110)
None
> Cloud Storage: add upgrading section

- upgrading.html.md.erb
[#184053110](https://www.pivotaltracker.com/story/show/184053110)
None
> GCP Storage: add example using public plan

- reference/gcp-storage.html.md.erb
Explains what GCP actions result when a binding is created
[#184334136](https://www.pivotaltracker.com/story/show/184334136)
- none
> storage: document what a binding means

- gcp-mysql-migration.html.md.erb
[#184048062](https://www.pivotaltracker.com/story/show/184048062)
No
> mysql: Migration from the legacy broker

- gcp-postgres-migration.html.md.erb
> postgres: Migration guide fixes

- release-notes.html.md.erb
[#184304315](https://www.pivotaltracker.com/story/show/184304315)
None
> Improved schema and documentation URL in Service Definition YAML files

- reference/gcp-mysql.html.md.erb
[#184346747](https://www.pivotaltracker.com/story/show/184346747)
None
> mysql: Explain binding

- release-notes.html.md.erb
[#184053111](https://www.pivotaltracker.com/story/show/184053111)
None
> GCP Storage: plans are configurable using Ops Manager

- release-notes.html.md.erb
[#184053111](https://www.pivotaltracker.com/story/show/184053111)
None
> GCP: New regions added to Ops Manager configuration

- release-notes.html.md.erb
[#184504690](https://www.pivotaltracker.com/story/show/184504690)
- none
> release notes: terraform update

- config/toc.md
- gcp-storage-migration.html.md.erb
- reference/gcp-storage.html.md.erb
[#184053109](https://www.pivotaltracker.com/story/show/184053109)
None
> GCP Storage: migration instructions

- .github/workflows/md-link-check.yml
- .github/workflows/mlc-config.json
- README.md
- reference/gcp-mysql.html.md.erb
- release-notes.html.md.erb
> 184494895 bug hunt fixes

- config/toc.md
- reference/gcp-mysql.html.md.erb
- reference/index.html.md.erb
- release-notes.html.md.erb
[#184048042](https://www.pivotaltracker.com/story/show/184048042)
> feat: MySQL GA

- reference/gcp-mysql.html.md.erb
- reference/gcp-storage.html.md.erb
> GCP Storage && MySQL: change default region value

- reference/gcp-mysql.html.md.erb
[#184048087](https://www.pivotaltracker.com/story/show/184048087)
- none
> mysql: note limitations of secure connections and MySQL 5.6

- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#184557377](https://www.pivotaltracker.com/story/show/184557377)
None
> chore: allow ARCHIVE option for storage_class

- reference/gcp-redis.html.md.erb
- release-notes.html.md.erb
- upgrading.html.md.erb
We also improve the upgrade part of the storage.
[#184517770](https://www.pivotaltracker.com/story/show/184517770)
None
> Redis: delete built-in plans

- config/toc.md
- reference/gcp-storage.html.md.erb
- reference/index.html.md.erb
- release-notes.html.md.erb
[#184053107](https://www.pivotaltracker.com/story/show/184053107)
None
> Storage: set Cloud Storage as GA

- release-notes.html.md.erb
[#184517770](https://www.pivotaltracker.com/story/show/184517770)
None
> GCP Storage: add aclaratory note to multiregional description

- upgrading.html.md.erb
Documentation was lagging behind and the default was changed in this pull request: [90](https://github.com/pivotal-cf/docs-csb-gcp/pull/90)
[#184053107](https://www.pivotaltracker.com/story/show/184053107)
None
> Storage: improve upgrading docs

- reference/gcp-postgresql.html.md.erb
- release-notes.html.md.erb
Note that GCP v1.2.0 has been abandoned due to not containing all the necessary changes, and v1.2.1 will be the next version.
[#184596268](https://www.pivotaltracker.com/story/show/184596268)
- 1.1
- 1.0
> postgres: document binding process and known issue

- reference/gcp-postgresql.html.md.erb
[#183641081](https://www.pivotaltracker.com/story/show/183641081)
- 1.2
- 1.1
- 1.0
> postgres: v15 not supported

- reference/gcp-mysql.html.md.erb
- reference/gcp-postgresql.html.md.erb
- reference/gcp-redis.html.md.erb
There were a few missing properties and type inconsistency
[#184613881](https://www.pivotaltracker.com/story/show/184613881)
- 1.2
- 1.1
- 1.0
> update properties to match brokerpak

- reference/gcp-redis.html.md.erb
[#184710879](https://www.pivotaltracker.com/story/show/184710879)
- 1.2
- 1.1
- 1.0
> fix a default value

- release-notes.html.md.erb
[#185029152](https://www.pivotaltracker.com/story/show/185029152)
None
> Resolved Issue: Document timeout increased

- upgrading.html.md.erb
> upgrade: improve upgrading instructions

- upgrading.html.md.erb
> upgrading: improve upgrade instructions

- installing-with-gcp.html.md.erb
- reference/gcp-mysql.html.md.erb
- reference/gcp-postgresql.html.md.erb
[#185200595](https://www.pivotaltracker.com/story/show/185200595)
None
> Authorized network: remove id to avoid confusion

- reference/gcp-postgresql.html.md.erb
- release-notes.html.md.erb
Which other branches should this be merged with (if any)? none
> fix: documentation for 1.2.2 release

- release-notes.html.md.erb
Which other branches should this be merged with (if any)? none
> fix: removing issue resolved in 1.2.2 not 1.3

- reference/gcp-postgresql.html.md.erb
- release-notes.html.md.erb
> postgres: add support for postgres 15

- release-notes.html.md.erb
- upgrading.html.md.erb
> Upgrade fails if there are instances pending upgrade

- gcp-postgres-migration.html.md.erb
[#186299520](https://www.pivotaltracker.com/story/show/186299520)
None
> Postgres: dollar symbol needs to be escaped

- reference/gcp-postgresql.html.md.erb
- release-notes.html.md.erb
[#182126463](https://www.pivotaltracker.com/story/show/182126463)
None
> Postgres: exposed property for High Availability

- gcp-postgres-migration.html.md.erb
[#186299520](https://www.pivotaltracker.com/story/show/186299520)
- 1.1
- 1.0
> Postgres: avoid bash commands when creating files

- release-notes.html.md.erb
> Delete database rows

- release-notes.html.md.erb
> upgrade terraform version

- release-notes.html.md.erb
[#186691637](https://www.pivotaltracker.com/story/show/186691637)
None
> docs: release notes for v1.3.1

- config/toc.md
- troubleshooting.html.md.erb
[#186536996](https://www.pivotaltracker.com/story/show/186536996)
- main
> docs: troubleshooting page with multiple update issue

- release-notes.html.md.erb
> We now fail deployment if there are upgrade errors

- release-notes.html.md.erb
> document new installation safety checks

- index.html.md.erb
[#187200917](https://www.pivotaltracker.com/story/show/187200917)
None
> docs: update documentation to not mention terraform anymore

- release-notes.html.md.erb
- upgrading.html.md.erb
[#187362878](https://www.pivotaltracker.com/story/show/187362878)
None
> chore: release notes - add missing items

- release-notes.html.md.erb
> chore: release notes for v1.5.1

- release-notes.html.md.erb
> Add marking in-progress operations as failed resolved issue

- gcp-storage-migration.html.md.erb
- reference/gcp-storage.html.md.erb
- release-notes.html.md.erb
[#187565525](https://www.pivotaltracker.com/story/show/187565525)
None
> fix: issue where Storage binding parameters do not work with Spring

- release-notes.html.md.erb
> add know issue where Storage binding parameters do not work with Spring

- release-notes.html.md.erb
[##187565525](https://www.pivotaltracker.com/story/show/187565525)
None
> Change release date

- reference/gcp-pubsub.html.md.erb
> Edit pupsub properties

- release-notes.html.md.erb
> Default_network_patch_release_notes

- reference/gcp-pubsub.html.md.erb
- reference/index.html.md.erb
- release-notes.html.md.erb
> Add_pubsub

- reference/gcp-pubsub.html.md.erb
> Subscription name cannot be updated

- release-notes.html.md.erb
> Add release notes for tofu version update

- reference/gcp-pubsub.html.md.erb
- release-notes.html.md.erb
[#187726204](https://www.pivotaltracker.com/story/show/187726204)
None
> PubSub: implement additional properties
